@rootUrl=http://localhost:8090/api/v1
@authEp={{rootUrl}}/auth

@bookEp = {{rootUrl}}/books

@borrowEP = {{rootUrl}}/borrows
POST {{authEp}}/login
Content-Type: application/json

{
    "email":"a@gmail.com",
    "password":"a"
}
###
PUT {{authEp}}
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzQxNzY5MTM2LCJleHAiOjE3NDE4NTU1MzZ9.coxzdY1pFc7IPtI4iO_ZGr0Sp7hSompbujoKTpzUySg

{
    "fName":"a"
}

### get all books by admin
GET {{bookEp}}
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzQxNjUzMzY5LCJleHAiOjE3NDE3Mzk3Njl9.DmormHeCKriz9_sOeoREBB1UEWioPD699rVDk_baZmk

### Renew jwt token 
GET {{authEp}}/renew-jwt
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzQxNTkwMTMzLCJleHAiOjE3NDI4ODYxMzN9.5c98H0qh6XZj00TCxZYwYSepURSIPf8JL8rPLjbzBBc

###
POST {{authEp}}/register
Content-Type: application/json

{
    "fName":"delte",
    "lName":"delete",
    "email":"delete@gmail.com",
    "password":"delete",
    "phone":"1"

}

###
GET {{authEp}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzM5ODQ2NzM5LCJleHAiOjE3Mzk5MzMxMzl9.1ohW3T6EXz2yI0GTgymVEkh3SocfaoM2bO3MimnftFM


### Logout user and invalidate jwt
GET {{authEp}}/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzQwMTMwNzcyLCJleHAiOjE3NDAyMTcxNzJ9.1-kIhwN2uYmi4LCpu0BeK4-PjtRDzmVVIoiIip_T9Ew


### Renew jwt token 
GET {{authEp}}/renew-jwt
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzQxNjQ0ODQ0LCJleHAiOjE3NDI5NDA4NDR9.Mqe9tdiEmADNcMvZHqeACy-sqAYDZGlml8UthauYz-I

### create book
POST {{bookEp}}
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzQwMTMyODA0LCJleHAiOjE3NDAyMTkyMDR9.GHX87JiIPLPZhtk_uJqi-9wACCa4w6v-DvbnfNW1E2g

{
   "title":"ishwor karki",
   "author":"ishowr",
   "thumbnail":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3fxbbEjr_4G1gNWSPOd5laur-yhcHAROH0A&sss",
   "isbn":"57596",
   "genre":"horror",
   "publishedYear":"2025"
}
### delete book
DELETE  {{bookEp}}/67b3fec88ffa34476f6478ea
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzQwMTMyODA0LCJleHAiOjE3NDAyMTkyMDR9.GHX87JiIPLPZhtk_uJqi-9wACCa4w6v-DvbnfNW1E2g
### update book
Put {{bookEp}}/67b84c047b3dd385ebed3e09
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzQwMTMyODA0LCJleHAiOjE3NDAyMTkyMDR9.GHX87JiIPLPZhtk_uJqi-9wACCa4w6v-DvbnfNW1E2g

{
   "title":"ishwor karki",
   "author":"ishowr",
   "thumbnail":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3fxbbEjr_4G1gssNWSPOd5laur-yhcHAROH0A&sss",
   "isbn":"524655444444",
   "genre":"horror",
   "publishedYear":"20"
}


###fetch filter books 
GET {{bookEp}}/pub-books?status=active



### get all books by admin
GET {{bookEp}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzQxMDUyMjg2LCJleHAiOjE3NDExMzg2ODZ9.5pAody1AvluR-o3bncCt1FnYRLCkG-2JjX1lHapmbFk


### 
GET {{authEp}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzQxNTY0MDkxLCJleHAiOjE3NDE1NjQxMjF9.9c5S8g4nmCOC4pu-Ex6gq4OgNCxTRLOChMU4RB-A0do


### 
POST  {{borrowEP}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzQxNjUzNjc4LCJleHAiOjE3NDE3NDAwNzh9.SfNNq4RfYeklj35Cv_31RSkWCiJa3Gd1AVN1T2cajZc
Content-Type: application/json

{
    "bookId": "67ceb52ee4f2da79c5b4f548",
    "title": "a",
    "thumbnail": "https://i1.sndcdn.com/avatars-000214145850-3zs8uo-t240x240.jpg"
}


### get all user admin
GET {{authEp}}/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzQxNzc4MDAwLCJleHAiOjE3NDE4NjQ0MDB9.SXmSxAxiSCy0QOsLvgWtKT4RxWTDVtdWuKZ0s95qYAs



### delete user 
DELETE  {{authEp}}/67d2aaedead9f5563cfe5ac9
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAZ21haWwuY29tIiwiaWF0IjoxNzQxODYwMDY1LCJleHAiOjE3NDE5NDY0NjV9.weLXEUo98V3qBLUpsnMTUSi7etmFRsqWSTp47GFj5GQ